CREATE TABLE IF NOT EXISTS comments (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  article_id BIGINT NOT NULL REFERENCES articles(id) ON DELETE CASCADE,
  author     TEXT NOT NULL,
  content    TEXT NOT NULL,
  date       TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE comments ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE policyname = '公开读取评论' AND tablename = 'comments'
  ) THEN
    CREATE POLICY "公开读取评论" ON comments FOR SELECT USING (true);
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE policyname = '公开创建评论' AND tablename = 'comments'
  ) THEN
    CREATE POLICY "公开创建评论" ON comments FOR INSERT WITH CHECK (true);
  END IF;
END $$;
