CREATE TABLE IF NOT EXISTS articles (
  id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title     TEXT NOT NULL,
  slug      TEXT NOT NULL UNIQUE,
  summary   TEXT,
  date      TEXT,
  tags      TEXT[] DEFAULT '{}',
  content   TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE articles ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE policyname = '公开读取' AND tablename = 'articles'
  ) THEN
    CREATE POLICY "公开读取" ON articles FOR SELECT USING (true);
  END IF;
END $$;

INSERT INTO articles (title, slug, summary, date, tags, content) VALUES
(
  '搭建个人博客的最佳实践',
  'best-practices-for-building-blog',
  '从零开始用 Next.js 搭建一个高性能的 Markdown 博客，涵盖路由、样式、SEO 等关键环节。',
  '2026-06-15',
  ARRAY['Next.js', '博客', '教程'],
  '## 为什么要自己搭博客

在 Medium、掘金、知乎这些平台写文章固然方便，但**数据不属于你**。拥有自己的博客意味着：

- 完全控制内容和样式
- 建立个人品牌
- 学习 Web 开发的最佳实战

## 技术选型

我们选择 Next.js 作为框架：

1. 基于 React，生态成熟
2. App Router 支持文件系统路由
3. 支持 SSG / SSR，SEO 友好
4. Vercel 一键部署

> 搭建博客是每个开发者的「成人礼」——你会在这个过程中理解路由、渲染策略、性能优化等关键概念。'
),
(
  'TypeScript 高级类型体操',
  'typescript-advanced-types',
  '深入理解条件类型、模板字面量类型、infer 关键字等 TS 高级特性，提升类型安全。',
  '2026-06-10',
  ARRAY['TypeScript', '类型系统'],
  '## 条件类型

TypeScript 的类型系统是图灵完备的。条件类型允许你根据类型关系做分支判断。

## infer 关键字

infer 是条件类型中最强大的特性，可以在类型推断中捕获类型变量。

## 模板字面量类型

从 TypeScript 4.1 开始，类型系统支持字符串拼接。

### 小结

这些高级类型在实际项目中能大幅减少运行时错误，让编译器帮你检查逻辑。'
),
(
  'Tailwind CSS 实战技巧',
  'tailwind-css-practical-tips',
  '整理 20 个日常开发中最常用的 Tailwind CSS 组合技，告别手写 CSS。',
  '2026-06-05',
  ARRAY['Tailwind CSS', 'CSS', '前端'],
  '## 为什么选 Tailwind

刚开始看到一堆 className 可能会觉得「这也太丑了」，但用上之后就会发现：

- 不用在 CSS 文件和组件之间来回切换
- 样式和 DOM 结构在同一视野内
- 设计系统内建（间距、颜色、字号都有阶梯）

## 实用组合技

### 1. 居中万能公式

```html
<div class="flex items-center justify-center h-screen">
  垂直水平居中
</div>
```

### 2. 卡片九件套

```html
<div class="bg-white rounded-lg shadow-sm border p-6 hover:shadow-md transition-shadow">
  优雅的卡片
</div>
```

> 工具类的价值不在于省了写 CSS 的时间，而在于约束你不写出随意的 magic number。'
),
(
  'React 服务端组件深度解析',
  'react-server-components-deep-dive',
  'RSC 是什么、解决了什么问题、和传统 SSR 有什么区别，一文讲清楚。',
  '2026-05-28',
  ARRAY['React', 'RSC', 'Next.js'],
  '## RSC 到底是什么

React Server Components（RSC）不是 SSR 的替代品，而是一种新的组件类型：

| 特性 | 服务端组件 | 客户端组件 |
|------|-----------|-----------|
| 运行位置 | 仅服务端 | 服务端 + 浏览器 |
| 使用 Hook | 不支持 | 支持 |
| 打包大小 | 0 KB | 包含在 bundle 中 |
| 访问数据库 | 直接访问 | 需要 API |

## 什么时候用客户端组件

需要 useState、useEffect、onClick 的才加 "use client"，其余默认服务端组件。

> 经验法则：需要交互的才加客户端组件。'
),
(
  '如何写出可维护的代码',
  'how-to-write-maintainable-code',
  '讨论命名规范、函数拆分、错误处理、测试策略等让代码活得久的实践经验。',
  '2026-05-20',
  ARRAY['工程实践', '代码质量'],
  '## 代码是写给人看的

如果你的代码需要同事盯着看 5 分钟才明白，那它就有改进空间。

## 命名原则

- 用动词开头命名函数：fetchUser、validateEmail
- 用名词命名变量：userList、isLoading
- 避免缩写：usr → user，fmt → format

## 函数拆分

一条简单的规则：一个函数只做一件事。

## 错误处理

- 不要吞掉错误：空 catch 块是定时炸弹
- 错误信息要包含上下文

> 可维护的代码不需要注释来解释「做了什么」——名字已经说明了一切。注释应该解释「为什么这样做」。'
)
ON CONFLICT (slug) DO NOTHING;
